name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Build App
      run: xcodebuild -project "PhotoGrid.xcodeproj" -scheme "PhotoGrid" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO      
    - name: Run tests
      run: xcodebuild clean test -project "PhotoGrid.xcodeproj" -scheme "PhotoGrid" -destination "platform=iOS Simulator,name=iPhone 11,OS=latest"

#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
      
#   deploy-dev:
#     runs-on: macos-latest
#     environment: 
#       name: dev
#       url: ''
#     needs: build
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: swift build -v
#       - name: Run tests
#         run: swift test -v
        
#   deploy-hmg:
#     runs-on: macos-latest
#     environment: 
#       name: hmg
#       url: ''
#     needs: deploy-dev
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: swift build -v
#       - name: Run tests
#         run: swift test -v 
        
#   deploy-prd:
#     runs-on: macos-latest
#     environment: 
#       name: prd
#       url: ''
#     needs: deploy-hmg
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: swift build -v
#       - name: Run tests
#         run: swift test -v
    
      
