name: Swift

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 12
      run: pwd && sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Init Package
      run: Swift package init --type library
    - name: Build
      run: |
        xcodebuild clean
        xcodebuild build -workspace PhotoGrid.xcworkspace -scheme "PhotoGrid (iOS)" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=latest" CODE_SIGN_ENTITLEMENT= DEVELOPMENT_TEAM= CODE_SIGNING_ALLOWED=NO      
    - name: Tests
      run: |
        xcodebuild clean
        xcodebuild test -workspace PhotoGrid.xcworkspace -scheme "PhotoGrid (iOS)" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=latest" CODE_SIGN_ENTITLEMENT= DEVELOPMENT_TEAM= CODE_SIGNING_ALLOWED=NO
      
      
  deploy-main:
    runs-on: macos-latest
    environment: 
      name: main
      url: 'google.com'
    needs: build
    steps:
      - name: Some script
        run: echo Deploy Main
