name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 12
      run: pwd && sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Init Package
      run: Swift package init --type library
    - name: Run Clean and Tests
      run: |
        xcodebuild clean
        xcodebuild test -workspace PhotoGrid.xcworkspace -scheme "PhotoGrid (iOS)" -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' CODE_SIGN_ENTITLEMENT= DEVELOPMENT_TEAM= CODE_SIGNING_ALLOWED=NO
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v

#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
      
#   deploy-dev:
#     runs-on: macos-latest
#     environment: 
#       name: dev
#       url: ''
#     needs: build
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: swift build -v
#       - name: Run tests
#         run: swift test -v
        
#   deploy-hmg:
#     runs-on: macos-latest
#     environment: 
#       name: hmg
#       url: ''
#     needs: deploy-dev
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: swift build -v
#       - name: Run tests
#         run: swift test -v 
        
#   deploy-prd:
#     runs-on: macos-latest
#     environment: 
#       name: prd
#       url: ''
#     needs: deploy-hmg
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build
#         run: swift build -v
#       - name: Run tests
#         run: swift test -v
    
      
